# setup-telegram.ps1 — Prépare backend + telegram-bot pour l'extension bonus (sans token BotFather)
# Usage: .\scripts\setup-telegram.ps1

$ErrorActionPreference = "Stop"
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$BackendEnv = Join-Path $RepoRoot "backend\.env"
$TelegramDir = Join-Path $RepoRoot "telegram-bot"
$TelegramEnv = Join-Path $TelegramDir ".env"
$TelegramExample = Join-Path $TelegramDir ".env.example"

$BotWallet = "0x7F48fa16c4535Bc00Ce6315E377F93787B95319F"

function Get-EnvVar {
  param([string]$Path, [string]$Name)
  if (-not (Test-Path $Path)) { return $null }
  foreach ($line in Get-Content $Path -Encoding UTF8) {
    if ($line -match "^\s*#") { continue }
    if ($line -match "^\s*$([regex]::Escape($Name))\s*=\s*(.*)\s*$") {
      $v = $Matches[1].Trim().Trim('"').Trim("'")
      if ($v.Length -gt 0) { return $v }
    }
  }
  return $null
}

function Set-EnvVarInFile {
  param([string]$Path, [string]$Name, [string]$Value)
  $escaped = $Value -replace '"', '\"'
  $newLine = "$Name=$escaped"
  if (-not (Test-Path $Path)) {
    New-Item -ItemType File -Path $Path -Force | Out-Null
    Add-Content -Path $Path -Value "# Generated by setup-telegram.ps1" -Encoding UTF8
    Add-Content -Path $Path -Value $newLine -Encoding UTF8
    return
  }
  $lines = Get-Content $Path -Encoding UTF8
  $found = $false
  $out = foreach ($line in $lines) {
    if ($line -match "^\s*$([regex]::Escape($Name))\s*=") {
      $found = $true
      $newLine
    } else {
      $line
    }
  }
  if (-not $found) {
    $out += $newLine
  }
  Set-Content -Path $Path -Value $out -Encoding UTF8
}

Write-Host "`n=== Configuration Telegram (bonus) ===" -ForegroundColor Cyan

if (-not (Test-Path $TelegramExample)) {
  throw "Fichier manquant: telegram-bot/.env.example"
}

if (-not (Test-Path $TelegramEnv)) {
  Copy-Item $TelegramExample $TelegramEnv -Force
  Write-Host "  telegram-bot/.env cree depuis .env.example" -ForegroundColor Green
}

if (-not (Test-Path $BackendEnv)) {
  $backendExample = Join-Path $RepoRoot "backend\.env.example"
  if (Test-Path $backendExample) {
    Copy-Item $backendExample $BackendEnv -Force
    Write-Host "  backend/.env cree depuis .env.example" -ForegroundColor Green
  } else {
    New-Item -ItemType File -Path $BackendEnv -Force | Out-Null
    Write-Host "  backend/.env cree (vide)" -ForegroundColor Yellow
  }
}

$serviceToken = Get-EnvVar -Path $BackendEnv -Name "BACKEND_SERVICE_TOKEN"
if (-not $serviceToken) {
  $bytes = New-Object byte[] 32
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  $serviceToken = "daa-" + [guid]::NewGuid().ToString("N") + [guid]::NewGuid().ToString("N")
  Write-Host "  BACKEND_SERVICE_TOKEN genere (aleatoire)" -ForegroundColor Green
} else {
  Write-Host "  BACKEND_SERVICE_TOKEN deja present dans backend/.env" -ForegroundColor Gray
}

Set-EnvVarInFile -Path $BackendEnv -Name "BACKEND_SERVICE_TOKEN" -Value $serviceToken
Set-EnvVarInFile -Path $BackendEnv -Name "BOT_SERVICE_WALLET_ADDRESS" -Value $BotWallet
Set-EnvVarInFile -Path $TelegramEnv -Name "BACKEND_SERVICE_TOKEN" -Value $serviceToken

$backendUrl = Get-EnvVar -Path $TelegramEnv -Name "BACKEND_URL"
if (-not $backendUrl) {
  Set-EnvVarInFile -Path $TelegramEnv -Name "BACKEND_URL" -Value "http://localhost:4000"
}

Write-Host "`n  BACKEND_SERVICE_TOKEN (backend + bot):" -ForegroundColor Cyan
Write-Host "  $serviceToken" -ForegroundColor White
Write-Host "  BOT_SERVICE_WALLET_ADDRESS=$BotWallet" -ForegroundColor Gray

Write-Host "`nProchaine etape (vous uniquement) :" -ForegroundColor Yellow
Write-Host "  Ajoutez TELEGRAM_BOT_TOKEN depuis @BotFather dans telegram-bot/.env" -ForegroundColor Yellow
Write-Host "  Puis redemarrez le backend et lancez:" -ForegroundColor Yellow
Write-Host "    .\scripts\start-dev.ps1   (demarre le bot si le token est present)" -ForegroundColor Yellow
Write-Host "    ou: npm run dev:telegram  (a la racine)" -ForegroundColor Yellow
Write-Host "`nRedemarrez le backend apres cette configuration.`n" -ForegroundColor Gray
